hamburguerblog/core/views.py
from flask import render_template,request,Blueprint
from flask.templating import render_template

from hamburguerblog.models import BlogPost

core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=10)
    return render_template('index.html', blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

hamburguerblog/posts/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from hamburguerblog import db
from hamburguerblog.models import BlogPost
from hamburguerblog.posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__)

# CREATE
@blog_posts.route("/create", methods=['GET', 'POST'])
@login_required
def create_post():

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data, text=form.text.data, user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()
        flash('Blog post created!!')
        return redirect(url_for('core.index'))

    return render_template('create_post.html', form=form)

# BLOG POST
@blog_posts.route("/<int:blog_post_id>")
@login_required
def blog_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title=blog_post.title, date=blog_post.date,post=blog_post)

# UPADATE
@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Blog post updated!!')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))

    #when the first view of the page the original title and etc.. willl be already pre-filled out
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html', title='Update',form=form)

# DELETE
@blog_posts.route("/<int:blog_post_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted!!')
    return redirect(url_for('core.index'))

hamburguerblog/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from hamburguerblog import db
from hamburguerblog.models import User, BlogPost
from hamburguerblog.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from hamburguerblog.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)


# register
@users.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        
        db.session.add(user)
        db.session.commit()
        flash('Thanks form registration!')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)

# log in
@users.route("/login", methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

                login_user(user)
                flash('Log in Sucess!')

                #if user is trying to visit a page that require a log in

                next = request.args.get('next')

                #if user not requested any page or the page is not homepage 
                if next == None or not next[0]=='/':
                    #next will be the homepage
                    next = url_for('core.index')
                    
                #if next is post.html e.g, then go to this page
                return redirect(next)

    return render_template('login.html', form=form)

# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))

# account
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account updated!')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

@users.route("/<username>")
@login_required
def user_post(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_post.html',user=user,blog_posts=blog_posts)

hamburguerblog/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div style='align-items: center;'>
        <h1>Welcome to the page for {{current_user.username}}</h1>
        <img src="{{url_for('static', filename='profile_pics/'+current_user.profile_image)}}">
    </div>
</div>

<div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.username.label(class="form-group")}}
            {{form.username(class="form-control")}}
        </div>
        <div class="form-group">
            {{form.email.label(class="form-group")}}
            {{form.email(class="form-control")}}
        </div>
        <div class="form-group">
            {{form.picture.label(class="form-group")}}
            {{form.picture(class="form-control")}}
        </div>
        <div class="form-group">
            {{form.submit(class="btn btn-primary")}}
        </div>
    </form>
</div>
{% endblock %}

hamburguerblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        <ul class="nav">
            <li class="nav-link">
                <a href="{{url_for('core.index')}}">Home</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('core.info')}}">About</a>
            </li>

            {% if current_user.is_authenticated %}
            <li class="nav-link">
                <a href="{{url_for('users.logout')}}">Log out</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.account')}}">Account</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('blog_posts.create_post')}}">Creat Post</a>
            </li>
            {% else %}
            <li class="nav-link">
                <a href="{{url_for('users.login')}}">Log in</a>
            </li>
            <li class="nav-link">
                <a href="{{url_for('users.register')}}">Register</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

hamburguerblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <h1>{{post.title}}</h1>
    <h2>Written by: {{post.author.username}}</h2>
    <h3>Published: {{post.date.strftime('%B %d, %Y')}}</h3>
    <p>{{post.text}}</p>

    {% if post.author == current_user %}
    <div>
      <a href="{{url_for('blog_posts.update_post',blog_post_id=post.id)}}">Update</a>
      <button type="button" class="btn btn-danger" data-toggle='modal' data-target="#del_modal">Delete</button>
    </div>
  
    {% endif %}
  </div>
  
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete the post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
  
          <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>

        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

hamburguerblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div class="container">
        <form class="form-group" method="POST">
            {{form.hidden_tag()}}

            <div class="form-group">
                {{form.title.label(class="form-control-label")}}
                {{form.title(class="form-control form-control-lg")}}    
            </div>
            <div class="form-group">
                {{form.text.label(class="form-control-label")}}
                {{form.text(class="form-control form-control-lg")}}    
            </div>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
</div>
{% endblock %}

hamburguerblog/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    {% if current_user.is_authenticated %}
    <h1>Good to see you here {{current_user.username}}</h1>
    {% else %}
    <h1>Hamburguer Blog</h1>
    <p>Share your Hamburguer here!!!</p>
    {% endif %}
</div>

<div class="container">
    {% for post in blog_posts.items %}
    <div class='card'>
        <div class="card-body">
            <h2><a class="card-title" href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
            <a href="{{url_for('users.user_post', username=post.author.username)}}">Written by: {{post.author.username}}</a>
            <p>Published on: {{post.date.strftime('%Y-%m-%d')}}</p>
            <p class="card-text">{{ post.text[:100] }}...</p>
            <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
          </div>
      </div>
    {% endfor %}

    <nav aria-label='Page Navigation example'>
        <ul class="pagination justify-content-center">
          {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)  %}
            {% if blog_posts.page == page_num %}
            <li class='page-item disabled'>
              <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{ page_num}}</a>
            </li>
            {% else %}
            <li class='page-item'>
              <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a>
            </li>
            {% endif %}
          {% endfor %}
        </ul>  
    </nav>

</div>
{% endblock %}

hamburguerblog/templates/info.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <h1>Info about this project</h1>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cum dolorum architecto laboriosam voluptas veniam, dignissimos nemo aspernatur magnam tenetur asperiores provident quos? Commodi cupiditate quo molestias repellendus obcaecati maiores dolorem!</p>
</div>
{% endblock %}

hamburguerblog/templates/login.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.submit()}}
</form>
{% endblock %}

hamburguerblog/templates/register.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.username.label}}{{form.username}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
    {{form.submit()}}
</form>
{% endblock %}

hamburguerblog/templates/user_blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <div>
            <h1>Welcome to the page for {{user.username}}</h1>
            <img src="{{url_for('static', filename='profile_pics/'+current_user.profile_image)}}">
        </div>
    </div>

{% for post in blog_posts.items %}
    <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
    Written By: <a href="{{url_for('users.user_post',username=post.author.username)}}">{{post.author.username}}</a>
    <p class="text-muted">Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
    <br>
    <p>{{post.text}}</p>
    <br>
{% endfor %}
</div>

<nav aria-label='Page Navigation example'>
    <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)  %}
        {% if blog_posts.page == page_num %}
        <li class='page-item disabled'>
          <a class="page-link" href="{{url_for('users.user_post',username=user.username,page=page_num)}}">{{ page_num}}</a>
        </li>
        {% else %}
        <li class='page-item'>
          <a class="page-link" href="{{url_for('users.user_post',username=user.username,page=page_num)}}">{{ page_num}}</a>
        </li>
        {% endif %}
      {% endfor %}
    </ul>  
</nav>

{% endblock %}

hamburguerblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <div>
            <h1>Welcome to the page for {{user.username}}</h1>
            <img src="{{url_for('static', filename='profile_pics/'+curent_user.profile_image)}}">
        </div>
    </div>

{% for post in blog_post.items %}
    <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
    Written By: <a href="{{url_for('user.user_post',username=post.author.username)}}">{{post.author}}</a>
    <p class="text-muted">Published on: {{post.date.strtime("%Y-%m-%d")}}</p>
    <br>
    <p>{{post.text}}</p>
    <br>
{% endfor %}
</div>

<nav aria-label='Page Navigation example'>
    <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)  %}
        {% if blog_posts.page == page_num %}
        <li class='page-item disabled'>
          <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
        </li>
        {% else %}
        <li class='page-item'>
          <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
        </li>
        {% endif %}
      {% endfor %}
    </ul>  
</nav>

{% endblock %}